// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SUP.CustomForm.ClientGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class PageListJsTemplate : PageListJsTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"//------------------------------全局函数------------------------------
//附件接收返回值
function AttachReturnValue(key, value) {
    AttachReturnRefresh(key, value);
}

//接收记账凭证回调
function PbFormCallback(data) {
    NG3IadCallback(data);
}

//编辑窗口保存关闭后回刷列表
function NG3Refresh() { 
	Ext.getCmp('");
            
            #line 14 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("grid\').store.load();\r\n}\r\n\r\n\r\n//------------------------------全局变量----------------" +
                    "--------------\r\nvar attfrom;  //附件打开自form、grid还是list\r\nvar Guid = new GUID();  //" +
                    "用于生成guid\r\nvar eform = \'");
            
            #line 21 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EForm));
            
            #line default
            #line hidden
            this.Write("\';  //工作流等的key \r\nvar busname = \'");
            
            #line 22 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PForm));
            
            #line default
            #line hidden
            this.Write("\';\r\nvar classname = \'");
            
            #line 23 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\';\r\nvar tablenameM = \'");
            
            #line 24 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("\';\r\nvar istask = \'");
            
            #line 25 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsTask));
            
            #line default
            #line hidden
            this.Write(@"';

var curToolbar;  //当前工具栏
var curGrid;  //当前grid
var curStore;  //当前store

var isMultiSelect = false;  //grid是否复选

//------------------------------onReady------------------------------
Ext.onReady(function () {
	//布局前初始化函数
    if (typeof allInitList === ""function"") {
        allInitList();
    }

	//工具栏
	var toolbarStr;

	if (IsSso == 'true') {
		toolbarStr = ['add', '->', '', 'close'];  //单点登录预览按钮特殊处理
	}
	else if (IsIad == '1') {
		toolbarStr = NG3IadButton();  //记账
	}
	else {
		toolbarStr = [");
            
            #line 50 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetButtons(Toolbar, "List")));
            
            #line default
            #line hidden
            this.Write("];\r\n\t}\r\n\r\n\tvar ngToolbar = Ext.create(\'Ext.ng.Toolbar\', {\r\n\t\tregion: \'north\',\r\n\t\t" +
                    "rightName: \'");
            
            #line 55 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QForm));
            
            #line default
            #line hidden
            this.Write("\', //权限名称\r\n\t\tid: \'toolbar\',\r\n\t\tngbuttons: toolbarStr\r\n\t});\r\n\r\n\t//定义模型\r\n\tExt.defin" +
                    "e(\'model\', {\r\n\t\textend: \'Ext.data.Model\',\r\n\t\tfields: [\r\n\t\t\t{\r\n\t\t\t\tname: \'");
            
            #line 65 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t\ttype: \'string\',\r\n\t\t\t\tmapping: \'");
            
            #line 67 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t},\r\n\t\t\t");
            
            #line 69 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetPageModelFields(gridPanel,"List",5)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t]\r\n\t});\r\n\r\n\tvar store = Ext.create(\'Ext.ng.JsonStore\', {\r\n\t\tmodel: \'model\',\r\n" +
                    "\t\tpageSize: 25,\r\n\t\tautoLoad: false,\r\n\t\turl: C_ROOT + \'");
            
            #line 77 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 77 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("List/GetList\'\r\n\t});\r\n\r\n\tvar pagingbar = Ext.create(\'Ext.ng.PagingBar\', {\r\n\t\titemI" +
                    "d: \'");
            
            #line 81 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("pagingbar\',\r\n\t\tstateId: \'");
            
            #line 82 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("grid\',\r\n\t\tstore: store\r\n\t});\r\n\r\n\t//列表panel\r\n\tvar grid = Ext.create(\'Ext.ng.GridPa" +
                    "nel\', {\r\n\t\tid: \'");
            
            #line 88 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("grid\',\r\n\t\tregion: \'center\',\r\n\t\tstateful: true,\r\n\t\tstateId: \'");
            
            #line 91 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("grid\',\r\n\t\tmultiSelect: isMultiSelect,\t\r\n\t\tstore: store,\r\n\t\tbuskey: \'");
            
            #line 94 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', //对应的业务表主键属性               \r\n\t\tcolumnLines: true,\r\n\t\tDbClickToView: false,\r\n\t\t" +
                    "columns: [");
            
            #line 97 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetPageGridColumns(gridPanel,"List",5)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t,{\r\n\t\t\t\theader: \'主键\',\r\n\t\t\t\tdataIndex: \'");
            
            #line 100 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t\thidden: true\r\n\t\t\t}],\r\n\t\tbbar: pagingbar\r\n\t});\r\n\r\n\t//内嵌查询panel，这个panel不放里面" +
                    "界面会错乱\r\n\tvar queryPanel = Ext.create(\'Ext.ng3.QueryPanel\', {\r\n\t\ttoolbar: ngToolba" +
                    "r,\r\n\t\tpageid: \"Web:");
            
            #line 109 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PForm));
            
            #line default
            #line hidden
            this.Write(@"List"", //对应内嵌查询业务点标识
		grid: grid,
		queryAutoLoad: Product.toUpperCase() == 'I8' ? false : true, //i8有项目树不自动load
		columnsPerRow: 4 //每行4列
	});

	//预览时内嵌查询设置按钮隐藏
	if (IsSso == 'true' && queryPanel.down('#queryset')) {
		queryPanel.down('#queryset').setVisible(false);
	}

	//布局面板数组
	var layoutItem = [ngToolbar, queryPanel, grid];

	//组织树
	var treeorgid = '';   //组织树上选中的组织
	var treeprojid = '';  //组织树上选中的项目
	if (Product.toUpperCase() == 'I8') {    
		var orgTreePanel = Ext.create('Ext.Gc.CommonLeftLayout', {
			id: 'CommonLeftLayout',
			region: 'west',
			cntmodel: '',
			width: 220,
			split: true,
			funcKey: '");
            
            #line 133 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EForm));
            
            #line default
            #line hidden
            this.Write(@"',  //业务点主键，不同的业务点记忆值不一样，树记忆有效的话该属性必须填
			changeCallBack: function () {
				treeorgid = this.belongorg;
				treeprojid = this.belongproj;
				store.load();
			}
		});

		store.on(""beforeload"", function (me, operation, eOpts) {
			Ext.apply(me.proxy.extraParams, {
				'clientfilter': Ext.JSON.encode({ CntType: Ext.getCmp(""CommonLeftLayout"").typefilter, OrgQuery: Ext.getCmp(""CommonLeftLayout"").orgfilter })
			});
		});

		layoutItem.push(orgTreePanel);
	}

           
    //布局
    var viewport = Ext.create('Ext.container.Viewport', {
        id: ""viewPort"",
        layout: 'border',
        items: layoutItem
    });


	//list 列表初始化时公共代码
	CommonReadyList();

");
            
            #line 162 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("add") || Toolbar.RNgButtons.Contains("add")) { 
            
            #line default
            #line hidden
            this.Write("    //新增\r\n\tif (ngToolbar.get(\'add\')) {\r\n\t\tngToolbar.get(\'add\').on(\'click\', functi" +
                    "on () {\r\n\t\t\tvar url = C_ROOT + \'");
            
            #line 166 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 166 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit?otype=add&issso=\' + IsSso;\r\n\t\t\t");
            
            #line 167 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(HasBlobdoc != "0" || HasReport != "0") { 
            
            #line default
            #line hidden
            this.Write("\t\t\turl += \'&ie=1\';\r\n\t\t\t");
            
            #line 169 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tif(defaultPc != 0) { \r\n\t\t\t\ttreeprojid = defaultPc;\r\n\t\t\t}\r\n\r\n\t\t\turl += \'&tree" +
                    "orgid=\' + treeorgid;\r\n\t\t\turl += \'&treeprojid=\' + treeprojid;\r\n\r\n\t\t\t$OpenTab(\'");
            
            #line 178 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("-新增\', url);\r\n\t\t});\r\n\t}\r\n");
            
            #line 181 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 183 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("edit") || Toolbar.RNgButtons.Contains("edit")) { 
            
            #line default
            #line hidden
            this.Write("    //修改\r\n\tif (ngToolbar.get(\'edit\')) {\r\n\t\tngToolbar.get(\'edit\').on(\'click\', func" +
                    "tion () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n        \r\n\t\t\t" +
                    "if (data.length > 0) {\r\n\t\t\t\tif (!RecodeRefresh(data, \'");
            
            #line 190 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 190 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 190 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/GetList')) { return; }

				var ischeck = data[0].get('ischeck');
				var is_wf = data[0].get('is_wf');

				if (EditBySelf==""Y""&&$appinfo.userID!=data[0].get('fillpsn')) {
					Ext.MessageBox.confirm('提示', '已设置仅允许修改自己的单据，是否以查看方式打开？', function (e) {
						if (e == ""yes"") {
							ngToolbar.get('view').fireEvent('click');
						} else {
							return;
						}
					});
				}

				else if (ischeck == '1' || is_wf == '1') {
					Ext.MessageBox.confirm('提示', '该单据已送审或已审核，不允许修改，是否以查看方式打开？', function (e) {
						if (e == ""yes"") {
							ngToolbar.get('view').fireEvent('click');
						} else {
							return;
						}
					});
				}
				else {
					var id = data[0].get('phid');
					var url = C_ROOT + '");
            
            #line 216 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 216 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit?otype=edit&id=\' + id;\r\n\t\t\t\t\t");
            
            #line 217 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(HasBlobdoc != "0" || HasReport != "0") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\turl += \'&ie=1\';\r\n\t\t\t\t\t");
            
            #line 219 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t$OpenTab(\'");
            
            #line 220 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("-修改\', url);\r\n\t\t\t\t}  \r\n\t\t\t}\r\n\t\t\telse {\r\n\t\t\t\tExt.MessageBox.alert(\'提示\', \'请选择行\');\r\n\t" +
                    "\t\t}\r\n\r\n\t\t});\r\n\t}\r\n");
            
            #line 229 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 231 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("copy") || Toolbar.RNgButtons.Contains("copy")) { 
            
            #line default
            #line hidden
            this.Write("    //复制\r\n\tif (ngToolbar.get(\'copy\')) {\r\n\t\tngToolbar.get(\'copy\').on(\'click\', func" +
                    "tion () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n        \r\n\t\t\t" +
                    "if (data.length > 0) {\r\n\t\t\t\tvar id = data[0].get(\'");
            
            #line 238 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\');\r\n\r\n\t\t\t\tvar url = C_ROOT + \'");
            
            #line 240 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 240 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit?otype=copy&id=\' + id;\r\n\t\t\t\t");
            
            #line 241 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(HasBlobdoc != "0" || HasReport != "0") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\turl += \'&ie=1\';\r\n\t\t\t\t");
            
            #line 243 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t$OpenTab(\'");
            
            #line 244 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("-复制\', url);\r\n\t\t\t}\r\n\t\t\telse{\r\n\t\t\t\tExt.MessageBox.alert(\'提示\', \'请选择行！\');\r\n\t\t\t}\r\n\t\t})" +
                    ";\r\n\t}\r\n");
            
            #line 251 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 253 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("delete") || Toolbar.RNgButtons.Contains("delete")) { 
            
            #line default
            #line hidden
            this.Write("\t//删除\r\n\tif (ngToolbar.get(\'delete\')) {\r\n\t\tngToolbar.get(\'delete\').on(\'click\', fun" +
                    "ction () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\r\n\t\t\tif (dat" +
                    "a.length > 0) {\r\n\t\t\t\tif (!RecodeRefresh(data, \'");
            
            #line 260 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 260 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 260 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/GetList')) { return; }

				//删除前检测函数
				if (typeof beforeDeleteList === ""function"") {
					if (!beforeDeleteList()) {
						return;
					}
				}

				if (DeleteBySelf == 'Y' && $appinfo.userID!=data[0].get('fillpsn') ) {
					Ext.MessageBox.alert('提示', '已设置为仅删除自己的单据，无法删除!');
					return;
				}

				var chkflg = data[0].get('ischeck');
				if (chkflg == ""1"") {
					Ext.MessageBox.alert('提示', '该单据已经审核，无法删除!');
					return;
				}

				chkflg = data[0].get('is_wf');
				if (chkflg == ""1"") {
					Ext.MessageBox.alert('提示', '该单据已送审，无法删除!');
					return;
				}
				

				var id = data[0].get('");
            
            #line 287 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write(@"');
				Ext.MessageBox.confirm('提示', '是否删除此记录？', function (e) {
					if (e == ""yes"") {
						Ext.Ajax.request({
							params: { 
								'id': id,
								'extendParam': typeof getSaveDataList === ""function"" ? getSaveDataList('Delete') : ''  //获取需保存数据
							},
							url: C_ROOT + '");
            
            #line 295 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 295 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/Delete',
							success: function (response) {
								var resp = Ext.JSON.decode(response.responseText);
								if (resp.status == ""OK"") {
									//刷新
									Ext.Array.each(data, function (record) {
										store.remove(record); //前端删除
									});
									Ext.MessageBox.alert('提示', '删除成功！');
								} else {
									Ext.MessageBox.alert('提示', '删除失败！');
								}
							}
						});
					} else {
						return;
					}  
				});
			}
			else{
				Ext.MessageBox.alert('提示', '请选择行！');
			}
		});
	}
");
            
            #line 319 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 321 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("view") || Toolbar.RNgButtons.Contains("view")) { 
            
            #line default
            #line hidden
            this.Write("    //查看\r\n\tif (ngToolbar.get(\'view\')) {\r\n\t\tngToolbar.get(\'view\').on(\'click\', func" +
                    "tion () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\r\n\t\t\tif (data" +
                    ".length > 0) {\r\n\t\t\t\tvar id = data[0].get(\'");
            
            #line 328 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\');\r\n\r\n\t\t\t\tvar url = C_ROOT + \'");
            
            #line 330 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 330 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit?otype=view&id=\' + id;\r\n\t\t\t\t");
            
            #line 331 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(HasBlobdoc != "0" || HasReport != "0") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\turl += \'&ie=1\';\r\n\t\t\t\t");
            
            #line 333 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t$OpenTab(\'");
            
            #line 334 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("-查看\', url);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n");
            
            #line 338 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 340 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("refresh") || Toolbar.RNgButtons.Contains("refresh")) { 
            
            #line default
            #line hidden
            this.Write("\t//刷新\r\n\tif (ngToolbar.get(\'refresh\')) {\r\n\t\tngToolbar.get(\'refresh\').on(\'click\', f" +
                    "unction () {\r\n\t\t\tstore.load();\r\n\t\t});\r\n\t}\r\n");
            
            #line 347 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 349 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("verify") || Toolbar.RNgButtons.Contains("verify")) { 
            
            #line default
            #line hidden
            this.Write("\t//审核\r\n\tif (ngToolbar.get(\'verify\')) {\r\n\t\tngToolbar.get(\'verify\').on(\'click\', fun" +
                    "ction () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\r\n\t\t\tif (dat" +
                    "a.length > 0) {\r\n\t\t\t\tif (!RecodeRefresh(data, \'");
            
            #line 356 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 356 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 356 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/GetList')) { return; }
			
			    if (CheckBySelf == 'Y' && $appinfo.userID==data[0].get('fillpsn') ) {
					Ext.MessageBox.alert('提示', '已设置为仅允许他人审核自己的单据!');
					return;
				}

				if (data[0].get('ischeck') == '1') {
                    Ext.MessageBox.alert('提示', '该单据已审核，不能重复审核!');
                    return;
                }

				//审核前检测函数
				if (typeof beforeVerifyList === ""function"") {
					if (!beforeVerifyList()) {
						return;
					}
				}
				
				var id = data[0].get('phid');
            
				Ext.Ajax.request({
					params: { 
						'id': id,
						'extendParam': typeof getSaveDataList === ""function"" ? getSaveDataList('Verify') : ''  //获取需保存数据
					},
					url: C_ROOT + '");
            
            #line 382 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 382 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/Verify',
					async: false, //同步请求
					success: function (response) {
						var resp = Ext.JSON.decode(response.responseText);
						if (resp.status === ""OK"") {
							Ext.MessageBox.alert('提示', ngToolbar.get('verify').text + ""成功!"");
							RecodeRefresh(data, '");
            
            #line 388 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 388 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 388 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("List/GetList\');\r\n\t\t\t\t\t\t} else {\r\n\t\t\t\t\t\t\tExt.MessageBox.alert( \'提示\', ngToolbar.get" +
                    "(\'verify\').text + \"失败!\");\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n");
            
            #line 397 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 399 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("unverify") || Toolbar.RNgButtons.Contains("unverify")) { 
            
            #line default
            #line hidden
            this.Write("\t//去审核\r\n\tif (ngToolbar.get(\'unverify\')) {\r\n\t\tngToolbar.get(\'unverify\').on(\'click\'" +
                    ", function () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\r\n\t\t\tif" +
                    " (data.length > 0) {\r\n\t\t\t\tif (!RecodeRefresh(data, \'");
            
            #line 406 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 406 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 406 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/GetList')) { return; }
			
			    if (CheckBySelf == 'Y' && $appinfo.userID==data[0].get('fillpsn') ) {
					Ext.MessageBox.alert('提示', '已设置为仅允许他人去审核自己的单据!');
					return;
				}

				if (data[0].get('ischeck') != '1') {
                    Ext.MessageBox.alert('提示', '该单据未审核，不能重复去审!');
                    return;
                }

				//去审核前检测函数
				if (typeof beforeUnVerifyList === ""function"") {
					if (!beforeUnVerifyList()) {
						return;
					}
				}

				var id = data[0].get('phid');
            
				Ext.Ajax.request({
					params: { 
						'id': id,
						'extendParam': typeof getSaveDataList === ""function"" ? getSaveDataList('UnVerify') : ''  //获取需保存数据
					},
					url: C_ROOT + '");
            
            #line 432 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 432 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/Verify',
					async: false, //同步请求
					success: function (response) {
						var resp = Ext.JSON.decode(response.responseText);
						if (resp.status === ""OK"") {
							Ext.MessageBox.alert('提示', ngToolbar.get('unverify').text + ""成功!"");
							RecodeRefresh(data, '");
            
            #line 438 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 438 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 438 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("List/GetList\');\r\n\t\t\t\t\t\t} else {\r\n\t\t\t\t\t\t\tExt.MessageBox.alert( \'提示\', ngToolbar.get" +
                    "(\'unverify\').text + \"失败!\");\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n");
            
            #line 447 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 449 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("check") || Toolbar.RNgButtons.Contains("check")) { 
            
            #line default
            #line hidden
            this.Write("    //送审\r\n\tif (ngToolbar.get(\'check\')) {\r\n\t\tngToolbar.get(\'check\').on(\'click\',fun" +
                    "ction(){\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\t\t\tif(data.len" +
                    "gth > 0){\r\n\t\t\t\tif (!RecodeRefresh(data, \'");
            
            #line 455 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 455 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 455 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"List/GetList')) { return; }

				chkflg = data[0].get('is_wf');
				if (chkflg == ""1"") {
					Ext.MessageBox.alert('提示', '该单据已送审，无法送审!');
					return;
				}
				//if (chkflg == ""2"") {
					//Ext.MessageBox.alert('提示', '该单据已送审完成，无法送审!');
					//return;
				//}

				var id = data[0].get('phid');
				$WorkFlow.startFlow('");
            
            #line 468 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EForm));
            
            #line default
            #line hidden
            this.Write("\', id, function () {\r\n\t\t\t\t\tRecodeRefresh(data, \'");
            
            #line 469 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', C_ROOT + \'");
            
            #line 469 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 469 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("List/GetList\');\r\n\t\t\t\t});\r\n\t\t\t}\r\n\t\t\telse{\r\n\t\t\t\tExt.MessageBox.alert(\'提示\', \'请选择行！\')" +
                    ";\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n");
            
            #line 477 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 479 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("history") || Toolbar.RNgButtons.Contains("history")) { 
            
            #line default
            #line hidden
            this.Write("\t//送审追踪\r\n\tif (ngToolbar.get(\'history\')) {\r\n\t\tngToolbar.get(\'history\').on(\'click\'," +
                    "function(){ \r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\t\t\tif(data" +
                    ".length > 0){\r\n\t\t\t\tvar id = data[0].get(\'phid\');\r\n\t\t\t\t$WorkFlow.showFlowInfo(\'");
            
            #line 486 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EForm));
            
            #line default
            #line hidden
            this.Write("\', id);\r\n\t\t\t}\r\n\t\t\telse{\r\n\t\t\t\tExt.MessageBox.alert(\'提示\', \'请选择行！\');\r\n\t\t\t}\r\n\t\t});\r\n\t" +
                    "}\r\n");
            
            #line 493 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 495 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("applycheck") || Toolbar.RNgButtons.Contains("applycheck")) { 
            
            #line default
            #line hidden
            this.Write(@"	//申请去审
	if (ngToolbar.get('applycheck')) {
		ngToolbar.get('applycheck').on('click',function(){ 
			if (!grid.getColumn('ocode')) {
				Ext.MessageBox.alert('提示', ""[设计问题]列表没有组织列"");
				return;
			}
			if (!grid.getColumn('checkpsn')) {
				Ext.MessageBox.alert('提示', ""[设计问题]列表没有审核人列"");
				return;
			}

			var data = grid.getSelectionModel().getSelection();
			if (data.length > 0) {

				var chkflg = data[0].get('ischeck');
				if (chkflg != ""1"") {
					Ext.MessageBox.alert('提示', '该单据未审核，不能申请去审!');
					return;
				}

				var id = data[0].get('phid');
				var billno = data[0].get('bill_no');
				var busTitle = '");
            
            #line 519 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("\';\r\n\t\t\t\tvar ocode = data[0].get(\'ocode\');\r\n\t\t\t\tvar receiverid = data[0].get(\'chec" +
                    "kpsn\');\r\n\t\t\t\tvar receivername = \'\';\r\n\t\t\t\tvar url = C_ROOT + \'");
            
            #line 523 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 523 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Edit?otype=view&id=' + id + '&ie=1&isapplycheck=1*web';

				if (grid.getColumn('checkpsn_name')) {
					receivername = data[0].get('checkpsn_name');
				}

				Ext.Ajax.request({
					params: {
						id: id,
						billno: billno,
						busTitle: busTitle,
						ocode: ocode,
						receiverid: receiverid,
						receivername: receivername,
						urlLink: url
					},
					url: C_ROOT + 'SUP/CustomCommon/ApplyCheckParam',
					async: false, //同步请求
					success: function (response) {
						var ret = response.responseText;                        
						var url = C_ROOT + 'SUP/ApplyCheck/ApplyCheck?params=' + ret;
						$OpenTab(busTitle + '-申请去审', url);
					}
				});
			}
		});
	}
");
            
            #line 550 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 552 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("attachment") || Toolbar.RNgButtons.Contains("attachment")) { 
            
            #line default
            #line hidden
            this.Write("\t//附件\r\n\tif (ngToolbar.get(\'attachment\')) {\r\n\t\tngToolbar.get(\'attachment\').on(\'cli" +
                    "ck\', function () {\r\n\t\t\tvar data = grid.getSelectionModel().getSelection();\r\n\t\t\ti" +
                    "f (data.length > 0) {\r\n\t\t\t\tOpenAttachment(\'list\', \'");
            
            #line 558 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridPanel.TableName));
            
            #line default
            #line hidden
            this.Write("\');\r\n\t\t\t}\r\n\t\t\telse{\r\n\t\t\t\tExt.MessageBox.alert(\'提示\', \'请选择行！\');\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n");
            
            #line 565 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 567 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 if(Toolbar.LNgButtons.Contains("print") || Toolbar.RNgButtons.Contains("print")) { 
            
            #line default
            #line hidden
            this.Write("    //打印\r\n\tif (ngToolbar.get(\'print\')) {\r\n\t\tngToolbar.get(\'print\').on(\'click\', fu" +
                    "nction () {\r\n\t\t\t$Print(\"");
            
            #line 571 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\", grid, \"");
            
            #line 571 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t});\r\n\t}\r\n");
            
            #line 574 "E:\NG3_Business\BusinessBaseClass\SUP\CustomForm\SUP.CustomForm.ClientGen\PageListJsTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write(@"
	//布局后初始化函数
	if (typeof allReadyList === ""function"") {
		allReadyList();
	}

	var frame = $GetWFrame();
    if (frame) {
        var listref = Ext.create('Ext.ng.ListRefresher', {
            listeners: {
                refreshlist: function () {
                    store.load();
                }
            }
        });

        frame.ListObserver.add(eform, listref);
    }

});");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class PageListJsTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
