// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SUP.CustomForm.ClientGen
{
    using System;
    
    
    #line 1 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class PageAppTemplate : PageAppTemplateBase
    {
        public virtual string TransformText()
        {
            this.Write("@{\r\n    ViewBag.Title = \"");
            
            #line 3 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit\";\r\n    Layout = \"~/Views/Shared/_Layout.cshtml\";\r\n}\r\n\r\n@section Script\r\n{  \r" +
                    "\n");
            
            #line 9 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("Supcan") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n<script src=\"@Url.Content(\"~/Resource/supcan/dynaload.js?89.5\")\" type=\"text/ja" +
                    "vascript\"></script>\r\n");
            
            #line 11 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("    <script type=\"text/javascript\">\r\n        var otype = \'@ViewBag.OType\';\r\n     " +
                    "   var busid = \'@ViewBag.ID\';\r\n\r\n");
            
            #line 16 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("Supcan") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n        function OnReady(id) {\r\n");
            
            #line 18 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            
            #line 19 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "Supcan"){
            
            #line default
            #line hidden
            
            #line 20 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 21 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }} 
            
            #line default
            #line hidden
            this.Write("     \r\n        }\r\n");
            
            #line 23 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n        Ext.onReady(function () {\r\n\r\n            //工具栏\r\n            var ngToolb" +
                    "ar = Ext.create(\'Ext.ng.Toolbar\', {\r\n                region: \'north\',\r\n         " +
                    "       ngbuttons: [\r\n                    ");
            
            #line 31 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetButtons(Toolbar)));
            
            #line default
            #line hidden
            this.Write("\r\n                ]\r\n            });\r\n");
            
            #line 34 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(tableLayouts.Fields.Count > 0 ) { 
            
            #line default
            #line hidden
            this.Write("            var mstform = Ext.create(\'Ext.ng.TableLayoutForm\', {\r\n               " +
                    " region: \'north\',\r\n                buskey: \'");
            
            #line 37 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PkPropertyname));
            
            #line default
            #line hidden
            this.Write("\', //对应的业务表主键\r\n                otype: otype,\r\n                columnsPerRow: ");
            
            #line 39 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableLayouts.ColumnsPerRow));
            
            #line default
            #line hidden
            this.Write(",\r\n                fields: [\r\n\t\t\t\t\t ");
            
            #line 41 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetForm(tableLayouts)));
            
            #line default
            #line hidden
            this.Write("\r\n                ]\r\n            });\r\n");
            
            #line 44 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("           \r\n            //布局\r\n            var viewport = Ext.create(\'Ext.contain" +
                    "er.Viewport\', {\r\n                id: \"viewPort\",\r\n                layout: \'borde" +
                    "r\',\r\n                items: [");
            
            #line 50 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.GetViewPortItems(fieldSets,panels,tableLayouts)));
            
            #line default
            #line hidden
            this.Write("]\r\n            });\r\n");
            
            #line 52 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < panels.Count; i++) { 
            
            #line default
            #line hidden
            
            #line 53 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        if(panels[i].Height<=0){ 
            
            #line default
            #line hidden
            this.Write("               ");
            
            #line 54 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(panels[i].TableName));
            
            #line default
            #line hidden
            this.Write("grid.hide(); \r\n");
            
            #line 55 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        }
            
            #line default
            #line hidden
            
            #line 56 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("\r\n            if (otype == $Otype.EDIT || otype == $Otype.VIEW) {\r\n              " +
                    "  Ext.Ajax.request({\r\n                    params: { \'id\': busid },\r\n            " +
                    "        url: \'@Url.Content(\"~/");
            
            #line 61 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 61 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit/GetMasterInfo\")\',\r\n                    success: function (response) {\r\n     " +
                    "                   var resp = Ext.JSON.decode(response.responseText);\r\n         " +
                    "               if (resp.Status === \"OK\") {\r\n                      ");
            
            #line 65 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(tableLayouts.Fields.Count > 0 & fieldSets.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                            var mstformobj = mstform.getForm();\r\n                " +
                    "            mstformobj.setValues(resp.Data); \r\n                      ");
            
            #line 68 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.BatchBindCombox(tableLayouts)));
            
            #line default
            #line hidden
            this.Write("                        \r\n                      ");
            
            #line 69 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("\r\n                      ");
            
            #line 71 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < fieldSets.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n                            var formobj");
            
            #line 72 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = fieldsetform");
            
            #line 72 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(".getForm();\r\n                            formobj");
            
            #line 73 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(".setValues(resp.Data);\r\n                      ");
            
            #line 74 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }     
            
            #line default
            #line hidden
            this.Write("\r\n                      ");
            
            #line 76 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Common.BatchBindCombox(fieldSets)));
            
            #line default
            #line hidden
            this.Write("\r\n \r\n                        } else {\r\n                            Ext.MessageBox" +
                    ".alert(\'取数失败\', resp.status);\r\n                        }\r\n                    }\r\n" +
                    "                });\r\n");
            
            #line 83 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
 for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("                //");
            
            #line 84 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("明细\r\n                Ext.apply(");
            
            #line 85 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.proxy.extraParams, { \'id\': busid, \'tabtype\': \'");
            
            #line 85 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("\' });\r\n                ");
            
            #line 86 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.cachePageData = false;\r\n                ");
            
            #line 87 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.load();\r\n                ");
            
            #line 88 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.cachePageData = true;\r\n");
            
            #line 89 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n\t\t\t//当新增时\r\n            if (otype == $Otype.ADD) {\r\n             " +
                    "   //清空主键\r\n");
            
            #line 95 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("AddInit") ) { 
            
            #line default
            #line hidden
            
            #line 96 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            
            #line 97 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "AddInit"){
            
            #line default
            #line hidden
            
            #line 98 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 99 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }}} 
            
            #line default
            #line hidden
            this.Write(" \r\n            }\r\n\r\n\t\t\t//当修改时\r\n            if (otype == $Otype.EDIT) {\r\n         " +
                    "   }\r\n\r\n\t\t\t//当查看时\r\n            if (otype == $Otype.VIEW) {\r\n                ngTo" +
                    "olbar.get(\'save\').hide();\r\n            }\r\n\r\n            //当不存在grid时\r\n           " +
                    " //if (");
            
            #line 112 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames.Count));
            
            #line default
            #line hidden
            this.Write(" == 0 ){\r\n                //ngToolbar.get(\'addrow\').hide();\r\n                //ng" +
                    "Toolbar.get(\'deleterow\').hide();    \r\n            //}    \r\n        \r\n   \r\n");
            
            #line 118 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("Normal") ) { 
            
            #line default
            #line hidden
            
            #line 119 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            
            #line 120 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "Normal"){
            
            #line default
            #line hidden
            
            #line 121 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 122 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }}} 
            
            #line default
            #line hidden
            this.Write("             \r\n\r\n");
            
            #line 124 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Toolbar.LNgButtons.Contains("addrow")||Toolbar.RNgButtons.Contains("addrow")) { 
            
            #line default
            #line hidden
            this.Write("            //增行\r\n            ngToolbar.items.get(\'addrow\').on(\'click\', function " +
                    "() {\r\n");
            
            #line 127 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("                \r\n                var data = ");
            
            #line 128 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[0]));
            
            #line default
            #line hidden
            this.Write("grid.getSelectionModel();\r\n                ");
            
            #line 129 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.insert(");
            
            #line 129 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.getCount(), data);\r\n\r\n                ");
            
            #line 131 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.getAt(");
            
            #line 131 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.data.items.length - 1).set(\'");
            
            #line 131 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("order\', ");
            
            #line 131 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.data.items.length);\r\n");
            
            #line 132 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        break;} 
            
            #line default
            #line hidden
            this.Write("            });\r\n");
            
            #line 134 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 136 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Toolbar.LNgButtons.Contains("deleterow")||Toolbar.RNgButtons.Contains("deleterow")) { 
            
            #line default
            #line hidden
            this.Write("            //删行\r\n            ngToolbar.items.get(\'deleterow\').on(\'click\', functi" +
                    "on () {\r\n");
            
            #line 139 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n                var data = ");
            
            #line 140 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("grid.getSelectionModel().getSelection();\r\n                if (data.length > 0) {\r" +
                    "\n                    Ext.Array.each(data, function (record) {\r\n                 " +
                    "       ");
            
            #line 143 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("store.remove(record); //前端删除\r\n                    });\r\n                    ");
            
            #line 145 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("grid.getView().refresh(true);\r\n                }\r\n");
            
            #line 147 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        break;} 
            
            #line default
            #line hidden
            this.Write("            });\r\n");
            
            #line 149 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 151 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("BeforeSave") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n            ");
            
            #line 152 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        int count= 1; 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 153 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 154 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "BeforeSave"){
            
            #line default
            #line hidden
            this.Write("function Validate");
            
            #line 155 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(count));
            
            #line default
            #line hidden
            this.Write("() {\r\n            ");
            
            #line 156 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
                count++;      
            
            #line default
            #line hidden
            
            #line 157 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\r\n};\r\n            ");
            
            #line 159 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }} 
            
            #line default
            #line hidden
            this.Write("              \r\n               \r\n");
            
            #line 161 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("\r\n            //保存\r\n            ngToolbar.get(\'save\').on(\'click\', function () {\r\n" +
                    "\r\n    ");
            
            #line 166 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(tableLayouts.Fields.Count > 0 ) { 
            
            #line default
            #line hidden
            this.Write("                var  vt = mstform.isValid();\r\n                if (!vt) {\r\n       " +
                    "             return;\r\n                }\r\n                var formData = mstform." +
                    "getFormData();  //同时有mstform 和 fieldsetform 怎么办?\r\n    ");
            
            #line 172 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    ");
            
            #line 175 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(fieldSets.Count >0)  { 
            
            #line default
            #line hidden
            this.Write("                var vf = fieldsetform0.isValid();\r\n                if (!vf) {\r\n  " +
                    "                  return;\r\n                }\r\n                var formData = fie" +
                    "ldsetform0.getFormData();\r\n    ");
            
            #line 181 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 183 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("BeforeSave") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 184 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        int count= 1; 
            
            #line default
            #line hidden
            
            #line 185 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            
            #line 186 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "BeforeSave"){
            
            #line default
            #line hidden
            this.Write("if(!Validate");
            
            #line 187 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(count));
            
            #line default
            #line hidden
            this.Write("())\r\n\treturn;\r\n");
            
            #line 189 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
                count++;      
            
            #line default
            #line hidden
            
            #line 190 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }}} 
            
            #line default
            #line hidden
            this.Write("    \r\n\r\n          ");
            
            #line 192 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n                var ");
            
            #line 193 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("Data = ");
            
            #line 193 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("grid.getChange();\r\n          ");
            
            #line 194 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 196 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("SaveUpdate") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n                var sqlstr=\"\";\r\n\t\t\t\tvar execstr=\"\";\r\n            ");
            
            #line 199 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        foreach (var item in Expressions){ 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 200 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(item.Value == "SaveUpdate"){
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 201 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 202 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            }}} 
            
            #line default
            #line hidden
            this.Write("  \r\n\r\n                Ext.Ajax.request({\r\n                    params: {\r\n        " +
                    "                \'formData\': formData\r\n                    ");
            
            #line 207 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n                        ,\'");
            
            #line 208 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("Data\':");
            
            #line 208 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("Data\r\n                    ");
            
            #line 209 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 210 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("SaveUpdate") ) { 
            
            #line default
            #line hidden
            this.Write("                        ,\'sql\': sqlstr \r\n\t\t\t\t\t\t,\'exec\': execstr\r\n                " +
                    "    ");
            
            #line 213 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("  \r\n                    },\r\n                    url: \'@Url.Content(\"~/");
            
            #line 215 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Area));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 215 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Edit/save\")\',\r\n                    success: function (response) {\r\n              " +
                    "          var resp = Ext.JSON.decode(response.responseText);\r\n                  " +
                    "      if (resp.Status === \"OK\") {\r\n                    ");
            
            #line 219 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(tableLayouts.Fields.Count > 0 ) { 
            
            #line default
            #line hidden
            this.Write("                            var formobj = mstform.getForm();\r\n                   " +
                    " ");
            
            #line 221 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 222 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(fieldSets.Count >0)  { 
            
            #line default
            #line hidden
            this.Write("                            var formobj = fieldsetform0.getForm();\r\n             " +
                    "       ");
            
            #line 224 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write(@"                            formobj.setValues(resp.Data);

                            Ext.MessageBox.alert('提示', ""保存成功"", function () {

                                var frame = $GetWFrame();
                                if (frame) {
                                    var listref = frame.ListObserver.get('");
            
            #line 231 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("List\');\r\n                              ");
            
            #line 232 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(tableLayouts.Fields.Count > 0 ) { 
            
            #line default
            #line hidden
            this.Write("                                    var data = mstform.getForm().getValues();\r\n  " +
                    "                            ");
            
            #line 234 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("                              ");
            
            #line 235 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(fieldSets.Count >0)  { 
            
            #line default
            #line hidden
            this.Write("                                    var data = fieldsetform0.getForm().getValues(" +
                    ");\r\n                              ");
            
            #line 237 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write(@"                                    listref.fireEvent('refreshlist', data);
                                }

                                $CloseTab();
                            });

                        } else {
                            Ext.MessageBox.alert('保存失败', resp.status);
                        }
                    }
                });
            });

");
            
            #line 251 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Toolbar.LNgButtons.Contains("print")||Toolbar.RNgButtons.Contains("print")) { 
            
            #line default
            #line hidden
            this.Write("            //打印\r\n            ngToolbar.get(\'print\').on(\'click\', function () {\r\n " +
                    "               var froms = [");
            
            #line 254 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
if(tableLayouts.Fields.Count > 0 ) { 
            
            #line default
            #line hidden
            this.Write("mstform");
            
            #line 254 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 255 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        if( tableLayouts.Fields.Count > 0  && fieldSets.Count>0){
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 255 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        }
            
            #line default
            #line hidden
            
            #line 256 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        else {
            
            #line default
            #line hidden
            this.Write(" ];");
            
            #line 256 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
        } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 258 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < fieldSets.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n        ");
            
            #line 259 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(i == fieldSets.Count-1){
            
            #line default
            #line hidden
            this.Write("fieldsetform");
            
            #line 259 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("];");
            
            #line 259 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
 }else{
            
            #line default
            #line hidden
            this.Write("fieldsetform");
            
            #line 259 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 259 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 260 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("        var grids = [");
            
            #line 261 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    for (int i = 0; i < PanelNames.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("   \r\n        ");
            
            #line 262 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            if(i == PanelNames.Count-1){
            
            #line default
            #line hidden
            
            #line 262 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("grid];");
            
            #line 262 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
}else{
            
            #line default
            #line hidden
            
            #line 262 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PanelNames[i]));
            
            #line default
            #line hidden
            this.Write("grid,");
            
            #line 262 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 263 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t$PrintForm(froms,grids);\r\n            });\r\n");
            
            #line 266 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("    \r\n        }); \r\n    </script>\r\n}\r\n");
            
            #line 270 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    if(Expressions.ContainsValue("Supcan") ) { 
            
            #line default
            #line hidden
            this.Write(" \r\n<div style=\"position:relative;width:800px;height:1px\" >\r\n   <script>insertFree" +
                    "Form(\'AF\', \'\')</script>\r\n</div>\r\n");
            
            #line 274 "D:\vs_mes\SUP\CustomForm\SUP.CustomForm.ClientGen\PageAppTemplate.tt"
    }
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class PageAppTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
